In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_column',150)
pd.set_option('display.max_row',60)

In [ ]:
df = pd.read_csv("loan_data.csv")
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE_x,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT_x,AMT_ANNUITY_x,AMT_GOODS_PRICE_x,NAME_TYPE_SUITE_x,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START_x,HOUR_APPR_PROCESS_START_x,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,...,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_PREV,NAME_CONTRACT_TYPE_y,AMT_ANNUITY_y,AMT_APPLICATION,AMT_CREDIT_y,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE_y,WEEKDAY_APPR_PROCESS_START_y,HOUR_APPR_PROCESS_START_y,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE_y,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,...,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1038818,Consumer loans,9251.775,179055.0,179055.0,0.0,179055.0,SATURDAY,9,Y,1,0.000000,NaN,NaN,XAP,Approved,-606,XNA,XAP,NaN,New,Vehicles,POS,XNA,Stone,500,Auto technology,24.0,low_normal,POS other with interest,365243.0,-565.0,125.0,-25.0,-17.0,0.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,...,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1810518,Cash loans,98356.995,900000.0,1035882.0,NaN,900000.0,FRIDAY,12,Y,1,NaN,NaN,NaN,XNA,Approved,-746,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
2,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,...,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2636178,Consumer loans,64567.665,337500.0,348637.5,0.0,337500.0,SUNDAY,17,Y,1,0.000000,NaN,NaN,XAP,Approved,-828,Cash through the bank,XAP,Family,Refreshed,Furniture,POS,XNA,Stone,1400,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0
3,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,...,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2396755,Consumer loans,6737.310,68809.5,68053.5,6885.0,68809.5,SATURDAY,15,Y,1,0.100061,NaN,NaN,XAP,Approved,-2341,Cash through the bank,XAP,Family,Refreshed,Consumer Electronics,POS,XNA,Country-wide,200,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0
4,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1564014,Consumer loans,5357.250,24282.0,20106.0,4860.0,24282.0,FRIDAY,5,Y,1,0.212008,NaN,NaN,XAP,Approved,-815,Cash through the bank,XAP,Unaccompanied,New,Mobile,POS,XNA,Regional / Local,30,Connectivity,4.0,middle,POS mobile without interest,365243.0,-784.0,-694.0,-724.0,-714.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1413696,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,Laborers,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0,0.0749,0.0526,0.9881,...,0.0805,NaN,0.00,NaN,block of flats,0.0718,Panel,No,0.0,0.0,0.0,0.0,-787.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,2073384,Cash loans,16400.610,229500.0,254340.0,NaN,229500.0,THURSDAY,12,Y,1,NaN,NaN,NaN,XNA,Approved,-648,Cash through the bank,XAP,NaN,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,24.0,middle,Cash X-Sell: middle,365243.0,-618.0,72.0,-558.0,-528.0,1.0
1413697,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,Laborers,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0,0.0749,0.0526,0.9881,...,0.0805,NaN,0.00,NaN,block of flats,0.0718,Panel,No,0.0,0.0,0.0,0.0,-787.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,1708056,Revolving loans,2250.000,45000.0,45000.0,NaN,45000.0,SUNDAY,14,Y,1,NaN,NaN,NaN,XAP,Refused,-456,XNA,HC,Unaccompanied,Repeater,XNA,Cards,walk-in,Country-wide,20,Connectivity,0.0,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
1413698,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,Laborers,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0,0.0749,0.0526,0.9881,...,0.0805,NaN,0.00,NaN,block of flats,0.0718,Panel,No,0.0,0.0,0.0,0.0,-787.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,1296007,Cash loans,30737.655,765000.0,1067940.0,NaN,765000.0,FRIDAY,14,Y,1,NaN,NaN,NaN,Repairs,Refused,-171,Cash through the bank,HC,Unaccompanied,Repeater,XNA,Cash,walk-in,Credit and cash offices,-1,XNA,60.0,low_normal,Cash Street: low,NaN,NaN,NaN,NaN,NaN,NaN
1413699,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,Laborers,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0,0.0749,0.0526,0.9881,...,0.0805,NaN,0.00,NaN,block of flats,0.0718,Panel,No,0.0,0.0,0.0,0.0,-787.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,2631384,Cash loans,54022.140,1170000.0,1271929.5,NaN,1170000.0,FRIDAY,14,Y,1,NaN,NaN,NaN,XNA,Approved,-787,Cash through the bank,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,AP+ (Cash loan),6,XNA,36.0,low_normal,Cash X-Sell: low,365243.0,-756.0,294.0,-66.0,-64.0,0.0
1413700,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,Laborers,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0,0.0749,0.0526,0.9881,...,0.0805,NaN,0.00,NaN,block of flats,0.0718,Panel,No,0.0,0.0,0.0,0.0,-787.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,2729207,Consumer loans,11514.555,58225.5,58545.0,5823.0,58225.5,FRIDAY,18,Y,1,0.098524,NaN,NaN,XAP,Approved,-500,Cash through the bank,XAP,NaN,Repeater,Computers,POS,XNA,Country-wide,20,Connectivity,6.0,high,POS mobile with interest,365243.0,-469.0,-319.0,-409.0,-400.0,0.0

In [4]:
df["NAME_CONTRACT_TYPE_x"].unique()

array(['Cash loans', 'Revolving loans'], dtype=object)

making Sample data from full dataset

In [21]:
from sklearn.model_selection import train_test_split

df_sample, _ = train_test_split(df, stratify=df['TARGET'], test_size=0.9, random_state=42)

In [22]:
print(df['TARGET'].value_counts(normalize=True))

TARGET
0    0.913447
1    0.086553
Name: proportion, dtype: float64

In [23]:
print(df_sample['TARGET'].value_counts(normalize=True))

TARGET
0    0.913447
1    0.086553
Name: proportion, dtype: float64

In [27]:
df_sample.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE_x,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT_x,AMT_ANNUITY_x,AMT_GOODS_PRICE_x,NAME_TYPE_SUITE_x,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START_x,HOUR_APPR_PROCESS_START_x,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,...,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_PREV,NAME_CONTRACT_TYPE_y,AMT_ANNUITY_y,AMT_APPLICATION,AMT_CREDIT_y,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE_y,WEEKDAY_APPR_PROCESS_START_y,HOUR_APPR_PROCESS_START_y,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE_y,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,316267,1,Cash loans,F,N,Y,1,126000.0,94810.5,7029.0,72000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.022625,-16392,-3808,-10527.0,-4289,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,MONDAY,16,0,0,0,0,0,0,Business Entity Type 3,0.666212,0.658620,NaN,0.066,0.0015,0.9727,NaN,NaN,0.0,0.1379,0.125,NaN,NaN,NaN,0.052,NaN,0.012,0.0672,0.0011,0.9727,NaN,NaN,0.0,0.1379,0.125,NaN,NaN,NaN,0.0526,NaN,0.0127,0.0666,0.0012,0.9727,...,0.0534,NaN,0.0122,NaN,block of flats,0.0443,Block,No,2.0,2.0,2.0,0.0,-2498.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1427446,Consumer loans,NaN,129703.50,129703.5,0.00,129703.50,SATURDAY,14,Y,1,0.000000,NaN,NaN,XAP,Refused,-450,Cash through the bank,HC,NaN,Repeater,Mobile,XNA,XNA,Country-wide,59,Connectivity,NaN,XNA,POS mobile with interest,NaN,NaN,NaN,NaN,NaN,NaN
1,362994,0,Cash loans,F,Y,Y,1,292500.0,1288350.0,37800.0,1125000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.003122,-16954,-2139,-5441.0,-505,28.0,1,1,0,1,0,0,Core staff,3.0,3,3,THURSDAY,15,0,1,1,0,1,1,Medicine,NaN,0.325949,0.622922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0.0,4.0,0.0,-1808.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1688124,Consumer loans,6204.285,89164.17,103284.0,1.17,89164.17,MONDAY,17,Y,1,0.000012,NaN,NaN,XAP,Approved,-899,Cash through the bank,XAP,"Spouse, partner",Repeater,Consumer Electronics,POS,XNA,Regional / Local,140,Consumer electronics,18.0,low_action,POS household without interest,365243.0,-868.0,-358.0,-688.0,-682.0,0.0
2,269856,1,Cash loans,F,N,N,1,112500.0,592560.0,35937.0,450000.0,Unaccompanied,Working,Secondary / secondary special,Widow,House / apartment,0.002134,-11338,-776,-752.0,-455,NaN,1,1,0,1,0,1,Managers,2.0,3,3,FRIDAY,5,0,0,0,0,0,0,Business Entity Type 3,0.298235,0.709773,0.368969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-623.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0,2284841,Cash loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,6,Y,1,NaN,NaN,NaN,XNA,Canceled,-239,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
3,365082,0,Cash loans,F,N,Y,1,135000.0,256500.0,14724.0,256500.0,Unaccompanied,Working,Higher education,Separated,House / apartment,0.028663,-10206,-807,-1316.0,-2638,NaN,1,1,0,1,1,1,NaN,2.0,2,2,FRIDAY,11,0,0,0,0,0,0,Other,0.634324,0.692981,0.604113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,3.0,0.0,-1186.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1716952,Cash loans,26546.355,112500.00,130918.5,NaN,112500.00,MONDAY,10,Y,1,NaN,NaN,NaN,XNA,Approved,-816,Cash through the bank,XAP,Children,Repeater,XNA,Cash,walk-in,Credit and cash offices,-1,XNA,6.0,high,Cash Street: high,365243.0,-786.0,-636.0,-786.0,-775.0,1.0
4,111114,0,Cash loans,M,Y,Y,0,225000.0,331632.0,32931.0,315000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.018850,-12107,-1569,-367.0,-4777,10.0,1,1,1,1,1,0,Laborers,2.0,2,2,THURSDAY,13,0,1,1,0,1,1,Construction,0.161766,0.424608,0.551381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-405.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,1725509,Cash loans,NaN,0.00,0.0,NaN,NaN,FRIDAY,13,Y,1,NaN,NaN,NaN,XNA,Canceled,-404,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,AP+ (Cash loan),100,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df_sample.reset_index(inplace=True,drop=True)

In [28]:
df_sample.to_csv("sample.csv", index=False)

feature reductions by seperating numeric and object columns

In [2]:
df_sample = pd.read_csv("sample.csv")

In [3]:
(df_sample.isnull().sum()/len(df_sample))*100

SK_ID_CURR                    0.000000
TARGET                        0.000000
NAME_CONTRACT_TYPE_x          0.000000
CODE_GENDER                   0.000000
FLAG_OWN_CAR                  0.000000
                               ...
DAYS_FIRST_DUE               39.690571
DAYS_LAST_DUE_1ST_VERSION    39.690571
DAYS_LAST_DUE                39.690571
DAYS_TERMINATION             39.690571
NFLAG_INSURED_ON_APPROVAL    39.690571
Length: 158, dtype: float64

In [4]:
null_percent = df_sample.isnull().mean() * 100
cols_to_drop = null_percent[null_percent > 60].index
cols_to_drop

Index(['OWN_CAR_AGE', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'FLOORSMIN_AVG',
       'LIVINGAPARTMENTS_AVG', 'NONLIVINGAPARTMENTS_AVG', 'YEARS_BUILD_MODE',
       'COMMONAREA_MODE', 'FLOORSMIN_MODE', 'LIVINGAPARTMENTS_MODE',
       'NONLIVINGAPARTMENTS_MODE', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI',
       'FLOORSMIN_MEDI', 'LIVINGAPARTMENTS_MEDI', 'NONLIVINGAPARTMENTS_MEDI',
       'FONDKAPREMONT_MODE', 'RATE_INTEREST_PRIMARY',
       'RATE_INTEREST_PRIVILEGED'],
      dtype='object')

In [5]:
df_sample.drop(columns=cols_to_drop, inplace=True)

In [6]:
df_sample.shape

(1413701, 139)

columns with high cardinality

In [20]:
for i in df_sample.select_dtypes(include='object').columns:
    print(f"{i} : {df_sample[i].nunique()}")

NAME_CONTRACT_TYPE_x : 2
CODE_GENDER : 3
FLAG_OWN_CAR : 2
FLAG_OWN_REALTY : 2
NAME_TYPE_SUITE_x : 7
NAME_INCOME_TYPE : 7
NAME_EDUCATION_TYPE : 5
NAME_FAMILY_STATUS : 5
NAME_HOUSING_TYPE : 6
OCCUPATION_TYPE : 18
WEEKDAY_APPR_PROCESS_START_x : 7
ORGANIZATION_TYPE : 58
HOUSETYPE_MODE : 3
WALLSMATERIAL_MODE : 7
EMERGENCYSTATE_MODE : 2
NAME_CONTRACT_TYPE_y : 4
WEEKDAY_APPR_PROCESS_START_y : 7
FLAG_LAST_APPL_PER_CONTRACT : 2
NAME_CASH_LOAN_PURPOSE : 25
NAME_CONTRACT_STATUS : 4
NAME_PAYMENT_TYPE : 4
CODE_REJECT_REASON : 9
NAME_TYPE_SUITE_y : 7
NAME_CLIENT_TYPE : 4
NAME_GOODS_CATEGORY : 26
NAME_PORTFOLIO : 5
NAME_PRODUCT_TYPE : 3
CHANNEL_TYPE : 8
NAME_SELLER_INDUSTRY : 11
NAME_YIELD_GROUP : 5
PRODUCT_COMBINATION : 17

In [7]:
# columns with high cardinality
df_sample.drop(columns=["ORGANIZATION_TYPE","NAME_CASH_LOAN_PURPOSE","NAME_GOODS_CATEGORY"], inplace=True)

# Filling missing values in categorical columns with user defined category
df_sample["OCCUPATION_TYPE"].fillna("Not mentioned", inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_3588\4135824603.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_sample["OCCUPATION_TYPE"].fillna("Not mentioned", inplace=True)

#### object columns null values imputing

In [8]:
df_objects = df_sample.select_dtypes(include=["object"]).copy()

In [23]:
(df_objects.isnull().sum()/len(df_sample))*100

NAME_CONTRACT_TYPE_x             0.000000
CODE_GENDER                      0.000000
FLAG_OWN_CAR                     0.000000
FLAG_OWN_REALTY                  0.000000
NAME_TYPE_SUITE_x                0.263139
NAME_INCOME_TYPE                 0.000000
NAME_EDUCATION_TYPE              0.000000
NAME_FAMILY_STATUS               0.000000
NAME_HOUSING_TYPE                0.000000
OCCUPATION_TYPE                 32.364717
WEEKDAY_APPR_PROCESS_START_x     0.000000
HOUSETYPE_MODE                  49.719177
WALLSMATERIAL_MODE              50.357926
EMERGENCYSTATE_MODE             47.015633
NAME_CONTRACT_TYPE_y             0.000000
WEEKDAY_APPR_PROCESS_START_y     0.000000
FLAG_LAST_APPL_PER_CONTRACT      0.000000
NAME_CONTRACT_STATUS             0.000000
NAME_PAYMENT_TYPE                0.000000
CODE_REJECT_REASON               0.000000
NAME_TYPE_SUITE_y               48.916319
NAME_CLIENT_TYPE                 0.000000
NAME_PORTFOLIO                   0.000000
NAME_PRODUCT_TYPE                0.000000
CHANNEL_TYPE                     0.000000
NAME_SELLER_INDUSTRY             0.000000
NAME_YIELD_GROUP                 0.000000
PRODUCT_COMBINATION              0.029002
dtype: float64

In [14]:
for i in df_objects.columns:
    if df_objects[i].isnull().sum() > 0:
        print(f"{i} : unique values",df_objects[i].unique(),"\n")

NAME_TYPE_SUITE_x : unique values ['Unaccompanied' 'Family' 'Spouse, partner' 'Group of people' 'Children'
 'Other_B' nan 'Other_A']

OCCUPATION_TYPE : unique values ['Laborers' 'Core staff' 'Managers' nan 'Drivers' 'Sales staff'
 'Cooking staff' 'IT staff' 'Accountants' 'Medicine staff'
 'High skill tech staff' 'Cleaning staff' 'Security staff'
 'Low-skill Laborers' 'Private service staff' 'Realty agents'
 'Waiters/barmen staff' 'HR staff' 'Secretaries']

HOUSETYPE_MODE : unique values ['block of flats' nan 'specific housing' 'terraced house']

WALLSMATERIAL_MODE : unique values ['Block' nan 'Panel' 'Stone, brick' 'Mixed' 'Wooden' 'Others' 'Monolithic']

EMERGENCYSTATE_MODE : unique values ['No' nan 'Yes']

NAME_TYPE_SUITE_y : unique values [nan 'Spouse, partner' 'Children' 'Unaccompanied' 'Family' 'Other_A'
 'Group of people' 'Other_B']

PRODUCT_COMBINATION : unique values ['POS mobile with interest' 'POS household without interest' 'Cash'
 'Cash Street: high' 'Cash Street: low' 'Cash X-Sell: middle'
 'POS household with interest' 'Card Street' 'Cash X-Sell: low'
 'POS industry with interest' 'Cash X-Sell: high'
 'POS industry without interest' 'Cash Street: middle' 'Card X-Sell'
 'POS mobile without interest' 'POS other with interest'
 'POS others without interest' nan]

In [9]:
for i in df_objects.columns:
    if df_objects[i].isnull().sum() > 0 and i != "OCCUPATION_TYPE":
        df_objects[i].fillna(df_objects[i].mode()[0],inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_3588\3866428344.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_objects[i].fillna(df_objects[i].mode()[0],inplace=True)

In [10]:
df_objects.isna().sum()

NAME_CONTRACT_TYPE_x            0
CODE_GENDER                     0
FLAG_OWN_CAR                    0
FLAG_OWN_REALTY                 0
NAME_TYPE_SUITE_x               0
NAME_INCOME_TYPE                0
NAME_EDUCATION_TYPE             0
NAME_FAMILY_STATUS              0
NAME_HOUSING_TYPE               0
OCCUPATION_TYPE                 0
WEEKDAY_APPR_PROCESS_START_x    0
HOUSETYPE_MODE                  0
WALLSMATERIAL_MODE              0
EMERGENCYSTATE_MODE             0
NAME_CONTRACT_TYPE_y            0
WEEKDAY_APPR_PROCESS_START_y    0
FLAG_LAST_APPL_PER_CONTRACT     0
NAME_CONTRACT_STATUS            0
NAME_PAYMENT_TYPE               0
CODE_REJECT_REASON              0
NAME_TYPE_SUITE_y               0
NAME_CLIENT_TYPE                0
NAME_PORTFOLIO                  0
NAME_PRODUCT_TYPE               0
CHANNEL_TYPE                    0
NAME_SELLER_INDUSTRY            0
NAME_YIELD_GROUP                0
PRODUCT_COMBINATION             0
dtype: int64

doing chiSquare test , mutual info and feature importance by RF

In [8]:
# Chi2 test
from sklearn.feature_selection import chi2
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import SelectKBest

X_encoded = df_objects.apply(LabelEncoder().fit_transform)
y_encoded = LabelEncoder().fit_transform(df_sample['TARGET'])

selector = SelectKBest(score_func=chi2, k=15)
selector.fit_transform(X_encoded, y_encoded)

selected_columns = X_encoded.columns[selector.get_support()].to_list()[:15]
print(selected_columns)

['NAME_CONTRACT_TYPE_x', 'CODE_GENDER', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_HOUSING_TYPE', 'WEEKDAY_APPR_PROCESS_START_x', 'WALLSMATERIAL_MODE', 'NAME_CONTRACT_STATUS', 'NAME_PAYMENT_TYPE', 'CODE_REJECT_REASON', 'NAME_TYPE_SUITE_y', 'CHANNEL_TYPE', 'NAME_SELLER_INDUSTRY', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION']

In [9]:
# Calculate Mutual Information for categorical features
from sklearn.metrics import mutual_info_score

mi_scores = []
for feature in df_objects.columns:
    mi = mutual_info_score(df_objects[feature], df_sample['TARGET'])
    mi_scores.append(mi)

In [10]:
mi_series = pd.Series(mi_scores, index=df_objects.columns)
ranked_categorical_features = mi_series.sort_values(ascending=False).index.tolist()

selected_features = ranked_categorical_features[:15]

print("Selected Features:", selected_features)

Selected Features: ['OCCUPATION_TYPE', 'NAME_INCOME_TYPE', 'PRODUCT_COMBINATION', 'CODE_REJECT_REASON', 'NAME_CONTRACT_STATUS', 'CODE_GENDER', 'NAME_EDUCATION_TYPE', 'NAME_YIELD_GROUP', 'NAME_SELLER_INDUSTRY', 'WALLSMATERIAL_MODE', 'NAME_FAMILY_STATUS', 'CHANNEL_TYPE', 'NAME_PRODUCT_TYPE', 'NAME_CONTRACT_TYPE_x', 'NAME_PORTFOLIO']

In [11]:
# Feature importance using RF classifier
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_encoded, y_encoded)

importances = rf.feature_importances_
rf_feature_importance = pd.Series(importances, index=X_encoded.columns)
rf_top_features = rf_feature_importance.sort_values(ascending=False).head(15).index.tolist()

In [29]:
rf_top_features

['WEEKDAY_APPR_PROCESS_START_y',
 'WEEKDAY_APPR_PROCESS_START_x',
 'OCCUPATION_TYPE',
 'NAME_FAMILY_STATUS',
 'CHANNEL_TYPE',
 'PRODUCT_COMBINATION',
 'NAME_TYPE_SUITE_x',
 'FLAG_OWN_REALTY',
 'WALLSMATERIAL_MODE',
 'NAME_YIELD_GROUP',
 'NAME_CLIENT_TYPE',
 'NAME_INCOME_TYPE',
 'NAME_HOUSING_TYPE',
 'FLAG_OWN_CAR',
 'NAME_SELLER_INDUSTRY']

In [12]:
# Intersection: features selected by all
intersection_obj = set(selected_columns) & set(rf_top_features) & set(selected_features)

# Union: features selected by any
union_obj = set(selected_columns) | set(rf_top_features) | set(selected_features)

print("Common Important Features (intersection):")
print(sorted(intersection_obj))

print("\nAll Selected Features (union):")
print(sorted(union_obj))

Common Important Features (intersection):
['CHANNEL_TYPE', 'NAME_INCOME_TYPE', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION', 'WALLSMATERIAL_MODE']

All Selected Features (union):
['CHANNEL_TYPE', 'CODE_GENDER', 'CODE_REJECT_REASON', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_CLIENT_TYPE', 'NAME_CONTRACT_STATUS', 'NAME_CONTRACT_TYPE_x', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'NAME_INCOME_TYPE', 'NAME_PAYMENT_TYPE', 'NAME_PORTFOLIO', 'NAME_PRODUCT_TYPE', 'NAME_SELLER_INDUSTRY', 'NAME_TYPE_SUITE_x', 'NAME_TYPE_SUITE_y', 'NAME_YIELD_GROUP', 'OCCUPATION_TYPE', 'PRODUCT_COMBINATION', 'WALLSMATERIAL_MODE', 'WEEKDAY_APPR_PROCESS_START_x', 'WEEKDAY_APPR_PROCESS_START_y']

with **Domain Knowledge** we gonna reduce the object features form all selected features

In [13]:
data = pd.read_csv("data_dictionary.csv")

In [14]:
data[data['Column'].isin(union_obj)]

,Column,Description,Special
3,CODE_GENDER,Gender of the client,NaN
4,FLAG_OWN_CAR,Flag if the client owns a car,NaN
5,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN
12,NAME_INCOME_TYPE,"Clients income type (businessman, working, mat...",NaN
13,NAME_EDUCATION_TYPE,Level of highest education the client achieved,NaN
14,NAME_FAMILY_STATUS,Family status of the client,NaN
15,NAME_HOUSING_TYPE,What is the housing situation of the client (r...,NaN
28,OCCUPATION_TYPE,What kind of occupation does the client have,NaN
89,WALLSMATERIAL_MODE,Normalized information about building where th...,normalized
139,NAME_CONTRACT_STATUS,"Contract status (approved, cancelled, ...) of ...",NaN
141,NAME_PAYMENT_TYPE,Payment method that client chose to pay for th...,NaN
142,CODE_REJECT_REASON,Why was the previous application rejected,NaN
144,NAME_CLIENT_TYPE,Was the client old or new client when applying...,NaN
146,NAME_PORTFOLIO,"Was the previous application for CASH, POS, CA...",NaN
147,NAME_PRODUCT_TYPE,Was the previous application x-sell o walk-in,NaN
148,CHANNEL_TYPE,Through which channel we acquired the client o...,NaN
150,NAME_SELLER_INDUSTRY,The industry of the seller,NaN
152,NAME_YIELD_GROUP,Grouped interest rate into small medium and hi...,grouped
153,PRODUCT_COMBINATION,Detailed product combination of the previous a...,NaN

In [22]:
df_objects["NAME_HOUSING_TYPE"].value_counts()

NAME_HOUSING_TYPE
House / apartment      126493
With parents             6203
Municipal apartment      5086
Rented apartment         1961
Office apartment         1166
Co-op apartment           461
Name: count, dtype: int64

In [11]:
df1 = df_objects[['CHANNEL_TYPE', 'CODE_GENDER', 'NAME_HOUSING_TYPE','FLAG_OWN_REALTY','FLAG_OWN_CAR', 'OCCUPATION_TYPE',
                  'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE','NAME_CLIENT_TYPE', 'NAME_FAMILY_STATUS', 
                  'NAME_TYPE_SUITE_x', 'PRODUCT_COMBINATION']].copy()

#### numeric columns null values imputing

In [12]:
df_num = df_sample.select_dtypes(include=['float64', 'int64']).copy()

In [ ]:
for i in df_num.columns:
    if df_num[i].isnull().sum() > 0:
        print(f'{i} , null % : {(df_num[i].isnull().sum()/len(df_sample))*100:.3f} , unique value :{df_num[i].nunique()}')

AMT_ANNUITY_x , null % : 0.011 , unique value :10978
AMT_GOODS_PRICE_x , null % : 0.091 , unique value :679
EXT_SOURCE_1 , null % : 56.374 , unique value :42753
EXT_SOURCE_2 , null % : 0.119 , unique value :67211
EXT_SOURCE_3 , null % : 17.188 , unique value :777
APARTMENTS_AVG , null % : 50.270 , unique value :1822
BASEMENTAREA_AVG , null % : 58.203 , unique value :3175
YEARS_BEGINEXPLUATATION_AVG , null % : 48.353 , unique value :218
ELEVATORS_AVG , null % : 52.848 , unique value :201
ENTRANCES_AVG , null % : 49.926 , unique value :227
FLOORSMAX_AVG , null % : 49.336 , unique value :289
LANDAREA_AVG , null % : 59.027 , unique value :2915
LIVINGAREA_AVG , null % : 49.709 , unique value :4333
NONLIVINGAREA_AVG , null % : 54.649 , unique value :2465
APARTMENTS_MODE , null % : 50.270 , unique value :682
BASEMENTAREA_MODE , null % : 58.203 , unique value :3225
YEARS_BEGINEXPLUATATION_MODE , null % : 48.353 , unique value :185
ELEVATORS_MODE , null % : 52.848 , unique value :26
ENTRANCES_MODE , null % : 49.926 , unique value :30
FLOORSMAX_MODE , null % : 49.336 , unique value :25
LANDAREA_MODE , null % : 59.027 , unique value :2930
LIVINGAREA_MODE , null % : 49.709 , unique value :4378
NONLIVINGAREA_MODE , null % : 54.649 , unique value :2492
APARTMENTS_MEDI , null % : 50.270 , unique value :1013
BASEMENTAREA_MEDI , null % : 58.203 , unique value :3168
YEARS_BEGINEXPLUATATION_MEDI , null % : 48.353 , unique value :200
ELEVATORS_MEDI , null % : 52.848 , unique value :44
ENTRANCES_MEDI , null % : 49.926 , unique value :45
FLOORSMAX_MEDI , null % : 49.336 , unique value :47
LANDAREA_MEDI , null % : 59.027 , unique value :2939
LIVINGAREA_MEDI , null % : 49.709 , unique value :4396
NONLIVINGAREA_MEDI , null % : 54.649 , unique value :2489
TOTALAREA_MODE , null % : 47.842 , unique value :4294
OBS_30_CNT_SOCIAL_CIRCLE , null % : 0.238 , unique value :30
DEF_30_CNT_SOCIAL_CIRCLE , null % : 0.238 , unique value :9
OBS_60_CNT_SOCIAL_CIRCLE , null % : 0.238 , unique value :29
DEF_60_CNT_SOCIAL_CIRCLE , null % : 0.238 , unique value :8
AMT_REQ_CREDIT_BUREAU_HOUR , null % : 11.596 , unique value :4
AMT_REQ_CREDIT_BUREAU_DAY , null % : 11.596 , unique value :8
AMT_REQ_CREDIT_BUREAU_WEEK , null % : 11.596 , unique value :8
AMT_REQ_CREDIT_BUREAU_MON , null % : 11.596 , unique value :23
AMT_REQ_CREDIT_BUREAU_QRT , null % : 11.596 , unique value :9
AMT_REQ_CREDIT_BUREAU_YEAR , null % : 11.596 , unique value :25
AMT_ANNUITY_y , null % : 21.730 , unique value :67788
AMT_DOWN_PAYMENT , null % : 52.889 , unique value :7585
AMT_GOODS_PRICE_y , null % : 22.537 , unique value :25895
RATE_DOWN_PAYMENT , null % : 52.889 , unique value :26688
CNT_PAYMENT , null % : 21.730 , unique value :35
DAYS_FIRST_DRAWING , null % : 39.477 , unique value :1926
DAYS_FIRST_DUE , null % : 39.477 , unique value :2891
DAYS_LAST_DUE_1ST_VERSION , null % : 39.477 , unique value :4448
DAYS_LAST_DUE , null % : 39.477 , unique value :2808
DAYS_TERMINATION , null % : 39.477 , unique value :2741
NFLAG_INSURED_ON_APPROVAL , null % : 39.477 , unique value :2

some numeric columns are cateorical in disguice , so we are using mean , median , KNN imputer.

In [80]:
impute_check = pd.DataFrame(index=df_num.columns)
impute_check['Null %'] = df_num.isnull().mean() * 100
impute_check['Unique'] = df_num.nunique()
impute_check['Skewness'] = df_num.skew()

impute_check = impute_check[impute_check['Null %'] > 0]

def decide_imputation(row):
    if row['Null %'] < 15:
        if abs(row['Skewness']) < 0.5 and row['Unique'] > 100:
            return 'Mean'
        elif row["Unique"]< 30 :
            return 'Mode'
        else:
            return 'Median'
    elif row['Null %'] < 50:
        return 'KNN or Median'
    else:
        return 'Consider Dropping or KNN'

impute_check['Suggested Imputation'] = impute_check.apply(decide_imputation, axis=1)

impute_check.sort_values(by='Null %', ascending=False, inplace=True)

In [87]:
impute_check

,Null %,Unique,Skewness,Suggested Imputation
LANDAREA_MODE,59.027375,2930,4.554493,Consider Dropping or KNN
LANDAREA_AVG,59.027375,2915,4.605403,Consider Dropping or KNN
LANDAREA_MEDI,59.027375,2939,4.529280,Consider Dropping or KNN
BASEMENTAREA_AVG,58.202589,3175,3.479655,Consider Dropping or KNN
BASEMENTAREA_MEDI,58.202589,3168,3.442765,Consider Dropping or KNN
BASEMENTAREA_MODE,58.202589,3225,3.358475,Consider Dropping or KNN
EXT_SOURCE_1,56.374054,42753,-0.080615,Consider Dropping or KNN
NONLIVINGAREA_MODE,54.648794,2492,6.618057,Consider Dropping or KNN
NONLIVINGAREA_MEDI,54.648794,2489,6.594803,Consider Dropping or KNN
NONLIVINGAREA_AVG,54.648794,2465,6.611472,Consider Dropping or KNN
AMT_DOWN_PAYMENT,52.888873,7585,22.707073,Consider Dropping or KNN
RATE_DOWN_PAYMENT,52.888873,26688,2.120019,Consider Dropping or KNN
ELEVATORS_AVG,52.847846,201,2.526798,Consider Dropping or KNN
ELEVATORS_MODE,52.847846,26,2.645455,Consider Dropping or KNN
ELEVATORS_MEDI,52.847846,44,2.546265,Consider Dropping or KNN
APARTMENTS_MEDI,50.270213,1013,2.678609,Consider Dropping or KNN
APARTMENTS_AVG,50.270213,1822,2.691606,Consider Dropping or KNN
APARTMENTS_MODE,50.270213,682,2.728627,Consider Dropping or KNN
ENTRANCES_MODE,49.925727,30,2.396184,KNN or Median
ENTRANCES_AVG,49.925727,227,2.404075,KNN or Median
ENTRANCES_MEDI,49.925727,45,2.394472,KNN or Median
LIVINGAREA_AVG,49.708566,4333,2.947300,KNN or Median
LIVINGAREA_MODE,49.708566,4378,2.974590,KNN or Median
LIVINGAREA_MEDI,49.708566,4396,2.940045,KNN or Median
FLOORSMAX_MEDI,49.336493,47,1.211719,KNN or Median
FLOORSMAX_MODE,49.336493,25,1.213780,KNN or Median
FLOORSMAX_AVG,49.336493,289,1.197708,KNN or Median
YEARS_BEGINEXPLUATATION_AVG,48.352550,218,-14.856238,KNN or Median
YEARS_BEGINEXPLUATATION_MODE,48.352550,185,-13.980796,KNN or Median
YEARS_BEGINEXPLUATATION_MEDI,48.352550,200,-14.846024,KNN or Median
TOTALAREA_MODE,47.841833,4294,2.832369,KNN or Median
DAYS_FIRST_DUE,39.476551,2891,4.665910,KNN or Median
DAYS_TERMINATION,39.476551,2741,1.286131,KNN or Median
DAYS_LAST_DUE_1ST_VERSION,39.476551,4448,2.800566,KNN or Median
DAYS_FIRST_DRAWING,39.476551,1926,-3.598342,KNN or Median
DAYS_LAST_DUE,39.476551,2808,1.389930,KNN or Median
NFLAG_INSURED_ON_APPROVAL,39.476551,2,0.714309,KNN or Median
AMT_GOODS_PRICE_y,22.537313,25895,3.083833,KNN or Median
AMT_ANNUITY_y,21.730212,67788,2.614327,KNN or Median
CNT_PAYMENT,21.729504,35,1.542498,KNN or Median
EXT_SOURCE_3,17.187522,777,-0.314213,KNN or Median
AMT_REQ_CREDIT_BUREAU_MON,11.595812,23,7.575193,Mode
AMT_REQ_CREDIT_BUREAU_DAY,11.595812,8,28.270370,Mode
AMT_REQ_CREDIT_BUREAU_WEEK,11.595812,8,8.130194,Mode
AMT_REQ_CREDIT_BUREAU_HOUR,11.595812,4,13.979980,Mode
AMT_REQ_CREDIT_BUREAU_YEAR,11.595812,25,0.911797,Mode
AMT_REQ_CREDIT_BUREAU_QRT,11.595812,9,2.273051,Mode
DEF_60_CNT_SOCIAL_CIRCLE,0.238382,8,4.426232,Mode
DEF_30_CNT_SOCIAL_CIRCLE,0.238382,9,3.840197,Mode
OBS_60_CNT_SOCIAL_CIRCLE,0.238382,29,2.540167,Mode
OBS_30_CNT_SOCIAL_CIRCLE,0.238382,30,2.533483,Median
EXT_SOURCE_2,0.118837,67211,-0.785070,Median
AMT_GOODS_PRICE_x,0.090543,679,1.234807,Median
AMT_ANNUITY_x,0.010610,10978,1.335597,Median

In [94]:
df_num.columns

Index(['SK_ID_CURR', 'TARGET', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT_x', 'AMT_ANNUITY_x', 'AMT_GOODS_PRICE_x',
       'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       ...
       'RATE_DOWN_PAYMENT', 'DAYS_DECISION', 'SELLERPLACE_AREA', 'CNT_PAYMENT',
       'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION',
       'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL'],
      dtype='object', length=108)

In [13]:
# Droping high null columns
df_num.drop(['LANDAREA_MODE', 'LANDAREA_AVG', 'LANDAREA_MEDI', 'BASEMENTAREA_AVG',
       'BASEMENTAREA_MEDI', 'BASEMENTAREA_MODE', 'EXT_SOURCE_1',
       'NONLIVINGAREA_MODE', 'NONLIVINGAREA_MEDI', 'NONLIVINGAREA_AVG', 'RATE_DOWN_PAYMENT', 'ELEVATORS_AVG',
       'ELEVATORS_MODE', 'ELEVATORS_MEDI', 'APARTMENTS_MEDI', 'APARTMENTS_AVG',
       'APARTMENTS_MODE'],axis=1,inplace=True)

In [14]:
# Mode imputation for numeric columns
mode = ['AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_DAY',
       'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_YEAR', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'DEF_60_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE',
       'OBS_60_CNT_SOCIAL_CIRCLE', 'OBS_30_CNT_SOCIAL_CIRCLE']

for i in mode:
       df_num[i].fillna(df_num[i].mode()[0],inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_3588\3487236449.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].mode()[0],inplace=True)

In [15]:
# Median imputation
for i in df_num.columns:
       if df_num[i].isnull().sum() > 0 and i not in mode:
              df_num[i].fillna(df_num[i].median(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_3588\734641602.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[i].fillna(df_num[i].median(),inplace=True)

In [34]:
df_num.isnull().sum()

SK_ID_CURR                   0
TARGET                       0
CNT_CHILDREN                 0
AMT_INCOME_TOTAL             0
AMT_CREDIT_x                 0
                            ..
DAYS_FIRST_DUE               0
DAYS_LAST_DUE_1ST_VERSION    0
DAYS_LAST_DUE                0
DAYS_TERMINATION             0
NFLAG_INSURED_ON_APPROVAL    0
Length: 91, dtype: int64

### Reducing features (considering only important columns for prediction)

In [103]:
# correlation with target variable (top 15)
correlation = df_num.corr()['TARGET'].sort_values(ascending=True).index.to_list()[:15]
print(correlation)

['EXT_SOURCE_3', 'EXT_SOURCE_2', 'DAYS_EMPLOYED', 'FLOORSMAX_AVG', 'FLOORSMAX_MEDI', 'FLOORSMAX_MODE', 'AMT_GOODS_PRICE_x', 'TOTALAREA_MODE', 'LIVINGAREA_AVG', 'LIVINGAREA_MEDI', 'REGION_POPULATION_RELATIVE', 'LIVINGAREA_MODE', 'FLAG_DOCUMENT_6', 'HOUR_APPR_PROCESS_START_y', 'AMT_CREDIT_x']

In [104]:
# feature selection using selectkBest (top 15)
from sklearn.feature_selection import SelectKBest, f_classif
X = df_num.drop(["TARGET"],axis=1)
y = df_num["TARGET"]

selector = SelectKBest(score_func=f_classif, k=15)
X_new = selector.fit_transform(X, y)

selected_columns = X.columns[selector.get_support()].to_list()[:15]
print(selected_columns)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: UserWarning: Features [11 57] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:113: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

['DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'FLAG_EMP_PHONE', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'FLOORSMAX_AVG', 'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_3', 'DAYS_DECISION']

In [105]:
# Point-biserial correlation (top 15)

from scipy.stats import pointbiserialr

result = {}
for i in df_num.columns:
    corr, p_value = pointbiserialr(df_num[i], df_num['TARGET'])
    result[i] = corr

corr_series = pd.Series(result).sort_values(ascending=False).index.to_list()[:15]
print(corr_series)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\_stats_py.py:5657: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rpb, prob = pearsonr(x, y)

['TARGET', 'DAYS_BIRTH', 'DAYS_LAST_PHONE_CHANGE', 'REGION_RATING_CLIENT_W_CITY', 'REGION_RATING_CLIENT', 'REG_CITY_NOT_WORK_CITY', 'DAYS_ID_PUBLISH', 'FLAG_EMP_PHONE', 'DAYS_REGISTRATION', 'FLAG_DOCUMENT_3', 'REG_CITY_NOT_LIVE_CITY', 'DAYS_DECISION', 'DEF_30_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'LIVE_CITY_NOT_WORK_CITY']

In [106]:
# feature selection using VarianceThreshold (top 15)
from sklearn.feature_selection import VarianceThreshold

vt_selector = VarianceThreshold(threshold=0.01)
vt_selector.fit(X)

vt_features = X.columns[vt_selector.get_support()].tolist()[:15]
print(vt_features)

['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT_x', 'AMT_ANNUITY_x', 'AMT_GOODS_PRICE_x', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_PHONE', 'FLAG_EMAIL', 'CNT_FAM_MEMBERS']

In [107]:
# Feature importance score using RF classifier
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X, y)

importances = rf.feature_importances_
rf_feature_importance = pd.Series(importances, index=X.columns)
rf_top_features = rf_feature_importance.sort_values(ascending=False).head(15).index.tolist()

In [108]:
rf_top_features

['EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'DAYS_BIRTH',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'SK_ID_CURR',
 'DAYS_LAST_PHONE_CHANGE',
 'AMT_ANNUITY_x',
 'DAYS_EMPLOYED',
 'AMT_CREDIT_x',
 'SK_ID_PREV',
 'DAYS_DECISION',
 'AMT_INCOME_TOTAL',
 'AMT_GOODS_PRICE_x',
 'REGION_POPULATION_RELATIVE']

In [ ]:
# Intersection: features selected by all
intersection_num = set(selected_columns) & set(rf_top_features) & set(vt_features)

# Union: features selected by any
union_num = set(selected_columns) | set(rf_top_features) | set(vt_features)

print("Common Important Features (intersection):")
print(sorted(intersection_num))

print("\nAll Selected Features (union):")
print(sorted(union_num))

Common Important Features (intersection):
['DAYS_BIRTH', 'DAYS_DECISION', 'DAYS_EMPLOYED', 'DAYS_ID_PUBLISH', 'DAYS_LAST_PHONE_CHANGE', 'DAYS_REGISTRATION', 'EXT_SOURCE_2', 'EXT_SOURCE_3']

All Selected Features (union):
['AMT_ANNUITY_x', 'AMT_CREDIT_x', 'AMT_GOODS_PRICE_x', 'AMT_INCOME_TOTAL', 'CNT_CHILDREN', 'CNT_FAM_MEMBERS', 'DAYS_BIRTH', 'DAYS_DECISION', 'DAYS_EMPLOYED', 'DAYS_ID_PUBLISH', 'DAYS_LAST_PHONE_CHANGE', 'DAYS_REGISTRATION', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'FLAG_DOCUMENT_3', 'FLAG_EMAIL', 'FLAG_EMP_PHONE', 'FLAG_PHONE', 'FLAG_WORK_PHONE', 'FLOORSMAX_AVG', 'REGION_POPULATION_RELATIVE', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'SK_ID_CURR', 'SK_ID_PREV']

we are taking union of all test and with **DOMAIN KNOWLEDGE** we are redusing the numeric features.

In [139]:
data[data['Column'].isin(union_num)]

,Column,Description
0,SK_ID_CURR,ID of loan in our sample
6,CNT_CHILDREN,Number of children the client has
7,AMT_INCOME_TOTAL,Income of the client
16,REGION_POPULATION_RELATIVE,Normalized population of region where client l...
17,DAYS_BIRTH,Client's age in days at the time of application
18,DAYS_EMPLOYED,How many days before the application the perso...
19,DAYS_REGISTRATION,How many days before the application did clien...
20,DAYS_ID_PUBLISH,How many days before the application did clien...
23,FLAG_EMP_PHONE,"Did client provide work phone (1=YES, 0=NO)"
24,FLAG_WORK_PHONE,"Did client provide home phone (1=YES, 0=NO)"
26,FLAG_PHONE,"Did client provide home phone (1=YES, 0=NO)"
27,FLAG_EMAIL,"Did client provide email (1=YES, 0=NO)"
29,CNT_FAM_MEMBERS,How many family members does client have
30,REGION_RATING_CLIENT,Our rating of the region where client lives (1...
31,REGION_RATING_CLIENT_W_CITY,Our rating of the region where client lives wi...
37,REG_CITY_NOT_LIVE_CITY,Flag if client's permanent address does not ma...
38,REG_CITY_NOT_WORK_CITY,Flag if client's permanent address does not ma...
42,EXT_SOURCE_2,Normalized score from external data source
43,EXT_SOURCE_3,Normalized score from external data source
51,FLOORSMAX_AVG,Normalized information about building where th...
95,DAYS_LAST_PHONE_CHANGE,How many days before application did client ch...
97,FLAG_DOCUMENT_3,Did client provide document 3
123,SK_ID_CURR,ID of loan in our sample
140,DAYS_DECISION,Relative to current application when was the d...

In [16]:
df2 = df_num[['TARGET','AMT_ANNUITY_x', 'AMT_CREDIT_x', 'AMT_GOODS_PRICE_x', 'AMT_INCOME_TOTAL',
             'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_LAST_PHONE_CHANGE', 'DAYS_REGISTRATION',
             'EXT_SOURCE_2', 'EXT_SOURCE_3', 'REGION_RATING_CLIENT']].copy()

In [17]:
df = pd.concat([df2,df1],axis=1,join='outer')
df

,TARGET,AMT_ANNUITY_x,AMT_CREDIT_x,AMT_GOODS_PRICE_x,AMT_INCOME_TOTAL,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_LAST_PHONE_CHANGE,DAYS_REGISTRATION,EXT_SOURCE_2,EXT_SOURCE_3,REGION_RATING_CLIENT,CHANNEL_TYPE,CODE_GENDER,NAME_HOUSING_TYPE,FLAG_OWN_REALTY,FLAG_OWN_CAR,OCCUPATION_TYPE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_CLIENT_TYPE,NAME_FAMILY_STATUS,NAME_TYPE_SUITE_x,PRODUCT_COMBINATION
0,1,24700.5,406597.5,351000.0,202500.0,-9461,-637,-1134.0,-3648.0,0.262949,0.139376,2,Stone,M,House / apartment,Y,N,Laborers,Working,Secondary / secondary special,New,Single / not married,Unaccompanied,POS other with interest
1,0,35698.5,1293502.5,1129500.0,270000.0,-16765,-1188,-828.0,-1186.0,0.622246,0.510090,1,Credit and cash offices,F,House / apartment,N,N,Core staff,State servant,Higher education,Repeater,Married,Family,Cash X-Sell: low
2,0,35698.5,1293502.5,1129500.0,270000.0,-16765,-1188,-828.0,-1186.0,0.622246,0.510090,1,Stone,F,House / apartment,N,N,Core staff,State servant,Higher education,Refreshed,Married,Family,POS industry with interest
3,0,35698.5,1293502.5,1129500.0,270000.0,-16765,-1188,-828.0,-1186.0,0.622246,0.510090,1,Country-wide,F,House / apartment,N,N,Core staff,State servant,Higher education,Refreshed,Married,Family,POS household with interest
4,0,6750.0,135000.0,135000.0,67500.0,-19046,-225,-815.0,-4260.0,0.555912,0.729567,2,Regional / Local,M,House / apartment,Y,Y,Laborers,Working,Secondary / secondary special,New,Single / not married,Unaccompanied,POS mobile without interest
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1413696,0,49117.5,675000.0,675000.0,157500.0,-16856,-1262,-787.0,-5128.0,0.708569,0.113922,1,Credit and cash offices,F,House / apartment,N,N,Laborers,Commercial associate,Higher education,Repeater,Married,Unaccompanied,Cash X-Sell: middle
1413697,0,49117.5,675000.0,675000.0,157500.0,-16856,-1262,-787.0,-5128.0,0.708569,0.113922,1,Country-wide,F,House / apartment,N,N,Laborers,Commercial associate,Higher education,Repeater,Married,Unaccompanied,Card Street
1413698,0,49117.5,675000.0,675000.0,157500.0,-16856,-1262,-787.0,-5128.0,0.708569,0.113922,1,Credit and cash offices,F,House / apartment,N,N,Laborers,Commercial associate,Higher education,Repeater,Married,Unaccompanied,Cash Street: low
1413699,0,49117.5,675000.0,675000.0,157500.0,-16856,-1262,-787.0,-5128.0,0.708569,0.113922,1,AP+ (Cash loan),F,House / apartment,N,N,Laborers,Commercial associate,Higher education,Repeater,Married,Unaccompanied,Cash X-Sell: low
1413700,0,49117.5,675000.0,675000.0,157500.0,-16856,-1262,-787.0,-5128.0,0.708569,0.113922,1,Country-wide,F,House / apartment,N,N,Laborers,Commercial associate,Higher education,Repeater,Married,Unaccompanied,POS mobile with interest

In [18]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
TARGET,1413701.0,0.086553,0.281179,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00
AMT_ANNUITY_x,1413701.0,27016.877952,13950.716221,1.615500e+03,16821.000000,24925.500000,34542.000000,2.250000e+05
AMT_CREDIT_x,1413701.0,587553.672718,384917.331385,4.500000e+04,270000.000000,508495.500000,807984.000000,4.050000e+06
AMT_GOODS_PRICE_x,1413701.0,527652.182600,353102.838204,4.050000e+04,238500.000000,450000.000000,679500.000000,4.050000e+06
AMT_INCOME_TOTAL,1413701.0,173316.043724,198573.372015,2.565000e+04,112500.000000,157500.000000,207000.000000,1.170000e+08
DAYS_BIRTH,1413701.0,-16321.052225,4344.557089,-2.520100e+04,-19980.000000,-16044.000000,-12739.000000,-7.489000e+03
DAYS_EMPLOYED,1413701.0,68702.027038,145277.704778,-1.791200e+04,-2828.000000,-1281.000000,-284.000000,3.652430e+05
DAYS_LAST_PHONE_CHANGE,1413701.0,-1084.700686,799.936851,-4.292000e+03,-1683.000000,-1011.000000,-396.000000,0.000000e+00
DAYS_REGISTRATION,1413701.0,-5003.232866,3551.050912,-2.467200e+04,-7510.000000,-4508.000000,-2001.000000,0.000000e+00
EXT_SOURCE_2,1413701.0,0.511494,0.191005,8.173617e-08,0.389385,0.562768,0.660564,8.549997e-01
EXT_SOURCE_3,1413701.0,0.493187,0.179102,5.272652e-04,0.380800,0.510090,0.621226,8.960095e-01
REGION_RATING_CLIENT,1413701.0,2.059638,0.495780,1.000000e+00,2.000000,2.000000,2.000000,3.000000e+00

12 columns are taken from each object and numeric columns, final data set contains of 24 columns.

In [19]:
# Final Cleaned Dataset for Modeling
df.to_csv('df_cleaned.csv',index=False)